import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import addUserApi, { getAllHotelsApi, getHotelByIdApi } from './AddUserApi';

const initialState = {
    countValue: 0,
    hotels:[],
    hotelInfo:{},
    hotelDetails:{
        visits:0,
        Drafts:0,
        Bookings:0
    },
};
export const addUserAsync = createAsyncThunk(
  'user/addUserAsync',
  async (data) => {
    const res = await addUserApi(data)
    return res;
  }
);
export const getAllHotelsAsync = createAsyncThunk(
  'user/getAllHotels',
  async () => {
    const res = await getAllHotelsApi()
    return res;
  }
);
export const getHotelByIdAsync = createAsyncThunk(
  'user/getHotelById',
  async (id) => {
    const res = await getHotelByIdApi(id)
    return res;
  }
);




export const addUserSlice = createSlice({
  name: 'user',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    increment: (state) => {
      state.countValue += 1;
    },
    incrementVisits: (state) => {   
    state.hotelDetails.visits += 1
    },
    incrementDrafts: (state) => {
      state.hotelDetails.Drafts += 1
    },
    incrementBookings: (state) => {
      state.hotelDetails.Bookings += 1
    }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(addUserAsync.pending, (state) => {
        state.status = 'loading';

      })
      .addCase(addUserAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.userDetails = action.payload

      })
      .addCase(getAllHotelsAsync.pending, (state) => {
        state.status = 'loading';

      })
      .addCase(getAllHotelsAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.hotels = action.payload.data

      })
      .addCase(getHotelByIdAsync.pending, (state) => {
        state.hotelInfo = null;
        state.status = 'loading';

      })
      .addCase(getHotelByIdAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.hotelInfo = action.payload.data
        state.hotelDetails = action.payload.hotelData

      })
  },
});

export const { increment , incrementVisits, incrementDrafts, incrementBookings } = addUserSlice.actions;

export default addUserSlice.reducer;